#ifndef NIEDERREITER_API_H
#define NIEDERREITER_API_H

#include "config.h"
#include "crypto_hash_sha512.h"

#define CRYPTO_SECRETKEYBYTES PRIVATE_KEY_BYTES
#define CRYPTO_PUBLICKEYBYTES PUBLIC_KEY_BYTES
#define CRYPTO_BYTES (SYNDROME_BYTES + crypto_hash_sha512_BYTES)

#define CRYPTO_VERSION 0.1.0

#endif /* NIEDERREITER_API_H */
